source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'JudSDK'
	pod 'JudPlugin', :git => 'https://github.com/kfeagle/JudPlugin.git'
end

target '<%= iOSProjectName %>' do
    common
end


